sudo: required
dist: trusty

language: haxe

os:
  - linux
  
haxe:
  - "3.4.0"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix interp
  - haxelib run travix neko
  - haxelib run travix node
  - haxelib run travix python
  #- haxelib run travix java
