sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
      
install:
  - npm install

script:
  - travix neko .
  - npm run travix node .
  - npm run travix php .
  - npm run travix js .
  - npm run travix python .