sudo: required
dist: trusty

language: node_js

os:
  - linux
      
install:
  - npm install haxeshim -g
  - npm install switchx -g
  - npm install lix.pm -g
  - switchx install
  - lix download
  - haxelib install travix

script:
  - haxelib run travix js
  - haxelib run travix node
