sudo: required
dist: trusty

language: node_js

os:
  - linux
      
install:
  - sudo npm install haxeshim -g
  - sudo npm install switchx -g
  - sudo npm install lix.pm -g
  - switchx install
  - lix download
  - haxelib install travix

script:
  - haxelib run travix js
  - haxelib run travix node
